//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alperkaand_proje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web.WebPages.Html;

    public partial class ilan_goster
    {
        public int ilan_no { get; set; }
        public DateTime ilan_tarihi { get; set; }
        public string FotoURL { get; set; }
        public int uyeid { get; set; }
        public byte plaka_id { get; set; }

        [Required(ErrorMessage = "İlçe Seçiniz")]
        public int ilce_id { get; set; }

        [Required(ErrorMessage = "Aracınızın Markasını Seçiniz")]
        public int tas_marka_id { get; set; }

        [Required(ErrorMessage = "Aracınızın Modelini Seçiniz")]
        public int tas_model_id { get; set; }

        [Range(10000, 999999999, ErrorMessage = "Fiyat Bilgisi İstenilen Aralikta Değil")]
        public decimal fiyat { get; set; }

        [Range(0, 10000000, ErrorMessage = "Km İstenilen Aralikta Değil")]
        public int km { get; set; }

        [Required(ErrorMessage = "Aracınızın Yakıt Tipini Seçiniz")]
        public byte yakit_tipi_id { get; set; }

        [Required(ErrorMessage = "Aracınızın Vites Tipini Seçiniz")]
        public byte vites_tip_id { get; set; }

        [Required(ErrorMessage = "Aracınızın Rengini Seçiniz")]
        public byte renk_id { get; set; }

        [Required(ErrorMessage = "Aracınızın Motor Gücünü Seçiniz")]
        public byte motor_gucu_id { get; set; }

        [Required(ErrorMessage = "Aracınızın Motor Hacmini Seçiniz")]
        public byte motor_hacmi_id { get; set; }

        [Required(ErrorMessage = "Aracınızın Kasa Tipini Seçiniz")]
        public byte kasa_tip_id { get; set; }

        [Required(ErrorMessage = "Açıklama Giriniz")]
        [StringLength(2000, MinimumLength = 20, ErrorMessage = "Açıklama en az 20, en fazla 1500 karakter içermelidir.")]
        public string acıklama { get; set; }

        [Required(ErrorMessage = "Aracınızın Varyantını Seçiniz")]
        public int varyant_id { get; set; }

        public bool takas { get; set; }

        [Required(ErrorMessage = "Aracınızın Türünü Seçiniz")]
        public int tas_tur_id { get; set; }

        [Required(ErrorMessage = "Aracınızın Üretim Yılını Seçiniz")]
        public int uretim_yil_id { get; set; }

        [Required(ErrorMessage = "Başlık Giriniz")]
        [StringLength(50, MinimumLength = 10, ErrorMessage = "Başlık en az 10, en fazla 50 karakter içermelidir.")]
        public string ilan_basligi { get; set; }

        // Navigation Properties
        public virtual tasit_turleri tasit_turleri { get; set; }
        public virtual uretim_yili uretim_yili { get; set; }
        public virtual ilceler ilceler { get; set; }
        public virtual kasa_tipleri kasa_tipleri { get; set; }
        public virtual tasit_markalari tasit_markalari { get; set; }
        public virtual tasit_modelleri tasit_modelleri { get; set; }
        public virtual motor_gucleri motor_gucleri { get; set; }
        public virtual motor_hacimleri motor_hacimleri { get; set; }
        public virtual renkler renkler { get; set; }
        public virtual sehirler sehirler { get; set; }
        public virtual uyeler uyeler { get; set; }
        public virtual varyantlar varyantlar { get; set; }
        public virtual vites_tipi vites_tipi { get; set; }
        public virtual yakit_tipleri yakit_tipleri { get; set; }

        public ilan_goster()
        {
            ilan_tarihi = DateTime.Now;
        }
    }


}
