//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alperkaand_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class motor_gucleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public motor_gucleri()
        {
            this.ilan_goster = new HashSet<ilan_goster>();
        }
    
        public byte motor_gucu_no { get; set; }
        public Nullable<int> motor_gucu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ilan_goster> ilan_goster { get; set; }
    }
}
