//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alperkaand_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasit_markalari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tasit_markalari()
        {
            this.ilan_goster = new HashSet<ilan_goster>();
            this.tasit_modelleri = new HashSet<tasit_modelleri>();
        }
    
        public int tas_marka_no { get; set; }
        public int uretim_yil_id { get; set; }
        public string tas_marka_adi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ilan_goster> ilan_goster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tasit_modelleri> tasit_modelleri { get; set; }
        public virtual uretim_yili uretim_yili { get; set; }
    }
}
