//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alperkaand_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uretim_yili
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uretim_yili()
        {
            this.ilan_goster = new HashSet<ilan_goster>();
            this.tasit_markalari = new HashSet<tasit_markalari>();
        }
    
        public int uretim_yili_no { get; set; }
        public int tas_tur_id { get; set; }
        public short yillar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ilan_goster> ilan_goster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tasit_markalari> tasit_markalari { get; set; }
        public virtual tasit_turleri tasit_turleri { get; set; }
    }
}
