//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alperkaand_proje.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;

    public partial class uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uyeler()
        {
            this.ilan_goster = new HashSet<ilan_goster>();
            KayitTarihi = DateTime.Now;
        }
    
        public int uyeno { get; set; }
        public string kuladi { get; set; }
        public string sifre { get; set; }
        public string uye_TC { get; set; }
        public string adsoyad { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public byte plaka_id { get; set; }
        public int ilce_id { get; set; }
       
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string uye_foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ilan_goster> ilan_goster { get; set; }
        public virtual ilceler ilceler { get; set; }
        public virtual sehirler sehirler { get; set; }

       
    }
}
